#!groovy
// Flask building job.
// Continuous Delivery part. Deploy to Production servers.

pipeline {
  agent any
  // every 5 mins go to Git & check for changes
  // triggers { pollSCM('H/5 * * * *') }
  
  options {
    timestamps()
  }

  environment {
    ARTIFACT_NAME = "makushatnik/flask_hello"
  }

  stages {
    stage("Code Lint") {
      steps {
        echo "Check code is right"
      }
    }
    stage("Test") {
      steps {
        echo " ============= Tests Started ========="
        sh 'pwd'
        sh 'python3 app_test.py'
      }
    }
    stage("Create docker image") {
      steps {
        echo " ============= Image creating Started ========="
        sh 'docker build -t $ARTIFACT_NAME .'
      }
    }
    stage("Docker login") {
      steps {
        echo " ============= Docker login ============="
        withCredentials([usernamePassword(credentialsId: 'dockerhub_official', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
          sh """
          docker login -u $USERNAME -p $PASSWORD
          """
        }
      }
    }
    stage("Deploy") {
      steps {
        echo " ============= Deploy Started ========="
        sh 'docker push $ARTIFACT_NAME'
        sh 'docker run --rm -p 8081:5000 -d $ARTIFACT_NAME'
      }
    }
  }
}
