---
- name: Deploy Animal's Sounds Application to AWS
  hosts: aws-server
  become: yes

  vars:
    home: /home/ec2-user
    flaskDir: /home/ec2-user/flask-app

  tasks:
  - name: Include Deploy Project source files
    include: include/deploy.yml

#  - name: Include Disabling Services & Ports
#    include: include/ufw.yml

  - name: Include Disabling Services & Ports
    include: include/iptables.yml

  - name: Include Nginx and SSL Config
    include: include/nginx.yml

  - name: Include Service activating
    include: include/service.yml

  - name: Include Security settings
    include: include/security.yml

  handlers:
  - name: Reload Nginx
    service: name=nginx state=reloaded enabled=yes

  - name: Restart Sshd
    service: name=sshd state=restarted enabled=yes

  - name: Start App
    service:
      name: animals
      state: restarted
      enabled: yes
      daemon_reload: true
