---
- name: Deploy Animal's Sounds Application to AWS
  hosts: aws-server
  become: yes

  vars:
    home: /home/ec2-user

  tasks:
  - name: Installing Python3 Virtual Environment library
    yum:  name=python3-venv state=latest

  - name: Make Project Dir
    file:
      path: "{{home}}/flask-app"
      state: directory

  - name: Create Venv in the Project Dir
    command: cd "{{home}}/flask-app" && python3 -m venv venv

  - name: Move Source Files to server
    copy:
      src: "{{item}}"
      dest: "{{home}}/flask-app"
      mode: 0774
    with_items:
      ['main.py','errors.py','animal.py']

  - name: Activating Virtual Environment
    command: source "{{home}}/flask-app/venv/bin/activate"

  - name: Installing Flask
    command: pip install Flask

  - name: Set a FLASK_APP global variable
    command: export FLASK_APP=main.py

#  - name: Run Flask Application
#    shell: flask run
#    async: 1
#    poll: 0

  - name: CUPS stopped
    command: systemctl stop cups

  - name: CUPS disabled
    command: systemctl disable cups

  - name: Install Nginx on RedHat
    yum: name=nginx state=latest
    when: ansible_os_family == "RedHat"

  - name: Install Nginx on RedHat
    apt: name=nginx state=latest
    when: ansible_os_family == "Debian"
    
  - name: Enable Nginx service
    command: systemctl enable nginx

  - name: Copy Nginx config
    copy:
      src: animals.conf
      dest: /etc/nginx/sites-enabled
      mode: 0755

  - name: Copy Nginx snippets
    copy:
      src: {{item}}
      dest: /etc/nginx/snippets
      mode: 0755
    with_items: ['self-signed.conf','ssl-params.conf']
    
  - name: Generate SSL certs
    shell: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt

  - name: Perfect forward secrecy adding
    shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

  - name: Restart Nginx
    command: systemctl restart nginx

  - name: Copy Animals Service config
    copy:
      src: animals.service
      desr: /etc/systemd/system
      mode: 0755

  - name: Enable Animals Service
    command: systemctl enable animals

  - name: Start Animals Service
    command: systemctl start animals

  - name: Disable root login
    lineinfile:
      path: /etc/passwd
      state: present
      line: root:x:0:0:root:/root:/sbin/nologin

  - name: Disable root login 2
    lineinfile:
      path: /etc/passwd
      state: absent
      line: root:x:0:0:root:/root:/bin/bash
    
  - name: Disable password login
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      line: PasswordAuthentication no

  - name: Disable password login 2
    lineinfile:
      path: /etc/ssh/sshd_config
      state: absent
      line: PasswordAuthentication yes

  - name: Restart sshd service
    command: systemctl restart sshd
