#!groovy
// Gin building job.
// Continuous Delivery part. Deploy to Production servers.

pipeline {
  agent any
  // every 5 mins go to Git & check for changes
  triggers { pollSCM('H/5 * * * *') }
  
  options {
    timestamps()
  }

  environment {
    ARTIFACT_NAME = "makushatnik/gin_hello"
  }

  stages {

    stage('Clone repository') {
      steps {
        git branch: 'dev', changelog: false, credentialsId: 'github-ssh', poll: false, url: 'git@github.com:makushatnik/devops-course.git'
      }
    }

    stage('Preparing') {
      steps {
        echo "============= Preparing Started ================"
        sh '''
        rm -rf ${WORKSPACE}/conf
        rm -rf ${WORKSPACE}/about
        rm -rf ${WORKSPACE}/animals_sounds
        rm -rf ${WORKSPACE}/awscli
        rm -rf ${WORKSPACE}/chatbot
        rm -rf ${WORKSPACE}/cloudform
        rm -rf ${WORKSPACE}/docker
        rm -rf ${WORKSPACE}/github
        rm -rf ${WORKSPACE}/kubernetes
        rm -rf ${WORKSPACE}/terraform
        rm -rf ${WORKSPACE}/til
        rm -rf ${WORKSPACE}/tricky_bash
        mv -f ${WORKSPACE}/exam/gin/* ${WORKSPACE}/
        rm -rf ${WORKSPACE}/exam
        mkdir -p ${WORKSPACE}/tests
        '''
      }
    }

    stage("SonarQube") {
      agent { docker {
          image 'newtmitch/sonar-scanner'
          args '-v /var/run/docker.sock:/var/run/docker.sock -v ${WORKSPACE}/conf:/usr/lib/sonar-scanner/conf \
          --network host'
          reuseNode true
      } }
      steps {
        echo "=========== Code Lint is started ============="
        sh 'sonar-scanner'
      }
    }

    stage("Test") {
      options { retry(3) }
      agent { docker {
          image 'golang'
          reuseNode true
      } }
      environment {
        XDG_CACHE_HOME='/tmp/.cache'
      }
      steps {
        echo "============= Tests Started ========="
        sh 'mkdir -p ${GOPATH}/src/webserver'
        sh 'cp -f ${WORKSPACE}/go.mod ${WORKSPACE}/go.sum ${WORKSPACE}/*.go ${GOPATH}/src/webserver'
        sh 'go get github.com/gin-gonic/gin'
        sh 'go get github.com/stretchr/testify/assert'
        sh 'go clean -cache'
        sh 'go test webserver -v -short'
      }
    }

    stage("Build") {
      agent { docker {
          image 'golang'
          reuseNode true
      } }
      environment {
        GO111MODULE='off'
        CGO_ENABLED=0
        GOOS='linux'
        XDG_CACHE_HOME='/tmp/.cache'
      }
      steps {
        echo "============= Build Started ========="
        sh 'mkdir -p ${GOPATH}/src/webserver'
        sh 'cp -f ${WORKSPACE}/go.mod ${WORKSPACE}/go.sum ${WORKSPACE}/*.go ${GOPATH}/src/webserver'
        sh 'go get github.com/gin-gonic/gin'
        sh 'go get github.com/stretchr/testify/assert'
        sh 'go build webserver'
      }
    }

    stage("Docker") {
      steps {
        echo " ============= Image creating Started ========="
        sh 'docker build -t $ARTIFACT_NAME:$BUILD_ID -t $ARTIFACT_NAME:latest .'
      }
    }

    stage("Deploy") {
      steps {
        echo " ============= Deploy Started ========="
        withDockerRegistry(credentialsId: 'dockerhub_official', url: '') {
          sh 'docker push $ARTIFACT_NAME:$BUILD_ID'
          sh 'docker push $ARTIFACT_NAME:latest'
        }
        sh 'docker run --rm -p 8082:8080 -d $ARTIFACT_NAME'
      }
    }
  }

  post {
    always {
      deleteDir()
    }
  }
}
