---
- name: Disable root login
  lineinfile:
    path: /etc/passwd
    regex: "^{{item.key}}:"
    line:  "{{item.key}}:{{item.value}}"
    state: present
  with_items:
    - { key: "root:x:0:0:root:/root", value: "/sbin/nologin"}

- name: Configure Sshd
  lineinfile:
    path:  /etc/ssh/sshd_config
    regex: "^{{item.key}}"
    line:  "{{item.key}} {{item.value}}"
    state: present
  with_items:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "AuthenticationMethods", value: "publickey" }
    - { key: "PubkeyAuthentication", value: "yes" }
  notify: Restart Sshd
