apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc
  containers:
  - image: makushatnik/backend
    name: backend
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27018
      protocol: TCP
