apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc
  containers:
  - image: makushatnik/frontend
    name: frontend
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27019
      protocol: TCP
